// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: famfun.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Filesize      int64                  `protobuf:"varint,5,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Resolution    string                 `protobuf:"bytes,6,opt,name=resolution,proto3" json:"resolution,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	HomeServerId  string                 `protobuf:"bytes,8,opt,name=home_server_id,json=homeServerId,proto3" json:"home_server_id,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    string                 `protobuf:"bytes,10,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_famfun_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{0}
}

func (x *VideoInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoInfo) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *VideoInfo) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *VideoInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoInfo) GetHomeServerId() string {
	if x != nil {
		return x.HomeServerId
	}
	return ""
}

func (x *VideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoInfo) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeServerId  string                 `protobuf:"bytes,1,opt,name=home_server_id,json=homeServerId,proto3" json:"home_server_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_famfun_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetHomeServerId() string {
	if x != nil {
		return x.HomeServerId
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_famfun_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeServerId  string                 `protobuf:"bytes,1,opt,name=home_server_id,json=homeServerId,proto3" json:"home_server_id,omitempty"`
	VideoIds      []string               `protobuf:"bytes,2,rep,name=video_ids,json=videoIds,proto3" json:"video_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_famfun_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetHomeServerId() string {
	if x != nil {
		return x.HomeServerId
	}
	return ""
}

func (x *HeartbeatRequest) GetVideoIds() []string {
	if x != nil {
		return x.VideoIds
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_famfun_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VideoListUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeServerId  string                 `protobuf:"bytes,1,opt,name=home_server_id,json=homeServerId,proto3" json:"home_server_id,omitempty"`
	VideoIds      []string               `protobuf:"bytes,2,rep,name=video_ids,json=videoIds,proto3" json:"video_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoListUpdate) Reset() {
	*x = VideoListUpdate{}
	mi := &file_famfun_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoListUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoListUpdate) ProtoMessage() {}

func (x *VideoListUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoListUpdate.ProtoReflect.Descriptor instead.
func (*VideoListUpdate) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{5}
}

func (x *VideoListUpdate) GetHomeServerId() string {
	if x != nil {
		return x.HomeServerId
	}
	return ""
}

func (x *VideoListUpdate) GetVideoIds() []string {
	if x != nil {
		return x.VideoIds
	}
	return nil
}

type GetVideoInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoInfoRequest) Reset() {
	*x = GetVideoInfoRequest{}
	mi := &file_famfun_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInfoRequest) ProtoMessage() {}

func (x *GetVideoInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInfoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoInfoRequest) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{6}
}

func (x *GetVideoInfoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetVideoInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Video         *VideoInfo             `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoInfoResponse) Reset() {
	*x = GetVideoInfoResponse{}
	mi := &file_famfun_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInfoResponse) ProtoMessage() {}

func (x *GetVideoInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInfoResponse.ProtoReflect.Descriptor instead.
func (*GetVideoInfoResponse) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideoInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetVideoInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetVideoInfoResponse) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

type GetThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThumbnailRequest) Reset() {
	*x = GetThumbnailRequest{}
	mi := &file_famfun_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailRequest) ProtoMessage() {}

func (x *GetThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailRequest.ProtoReflect.Descriptor instead.
func (*GetThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{8}
}

func (x *GetThumbnailRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThumbnailResponse) Reset() {
	*x = GetThumbnailResponse{}
	mi := &file_famfun_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailResponse) ProtoMessage() {}

func (x *GetThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailResponse.ProtoReflect.Descriptor instead.
func (*GetThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{9}
}

func (x *GetThumbnailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetThumbnailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetThumbnailResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetPlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistRequest) Reset() {
	*x = GetPlaylistRequest{}
	mi := &file_famfun_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistRequest) ProtoMessage() {}

func (x *GetPlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistRequest) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlaylistRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GetPlaylistRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetPlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistResponse) Reset() {
	*x = GetPlaylistResponse{}
	mi := &file_famfun_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistResponse) ProtoMessage() {}

func (x *GetPlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistResponse.ProtoReflect.Descriptor instead.
func (*GetPlaylistResponse) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{11}
}

func (x *GetPlaylistResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetPlaylistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPlaylistResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetPlaylistResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	SegmentName   string                 `protobuf:"bytes,2,opt,name=segment_name,json=segmentName,proto3" json:"segment_name,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentRequest) Reset() {
	*x = GetSegmentRequest{}
	mi := &file_famfun_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentRequest) ProtoMessage() {}

func (x *GetSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentRequest.ProtoReflect.Descriptor instead.
func (*GetSegmentRequest) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{12}
}

func (x *GetSegmentRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GetSegmentRequest) GetSegmentName() string {
	if x != nil {
		return x.SegmentName
	}
	return ""
}

func (x *GetSegmentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentResponse) Reset() {
	*x = GetSegmentResponse{}
	mi := &file_famfun_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentResponse) ProtoMessage() {}

func (x *GetSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentResponse.ProtoReflect.Descriptor instead.
func (*GetSegmentResponse) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{13}
}

func (x *GetSegmentResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSegmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetSegmentResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UpdateVideoInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    string                 `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoInfoRequest) Reset() {
	*x = UpdateVideoInfoRequest{}
	mi := &file_famfun_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoInfoRequest) ProtoMessage() {}

func (x *UpdateVideoInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoInfoRequest) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateVideoInfoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpdateVideoInfoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVideoInfoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateVideoInfoRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type UpdateVideoInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Video         *VideoInfo             `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoInfoResponse) Reset() {
	*x = UpdateVideoInfoResponse{}
	mi := &file_famfun_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoInfoResponse) ProtoMessage() {}

func (x *UpdateVideoInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateVideoInfoResponse) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateVideoInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateVideoInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateVideoInfoResponse) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

type UploadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Filesize      int64                  `protobuf:"varint,2,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	HomeServerId  string                 `protobuf:"bytes,4,opt,name=home_server_id,json=homeServerId,proto3" json:"home_server_id,omitempty"`
	TotalChunks   uint32                 `protobuf:"varint,5,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_famfun_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{16}
}

func (x *UploadVideoRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadVideoRequest) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *UploadVideoRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UploadVideoRequest) GetHomeServerId() string {
	if x != nil {
		return x.HomeServerId
	}
	return ""
}

func (x *UploadVideoRequest) GetTotalChunks() uint32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *UploadVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UploadVideoChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoChunk) Reset() {
	*x = UploadVideoChunk{}
	mi := &file_famfun_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoChunk) ProtoMessage() {}

func (x *UploadVideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoChunk.ProtoReflect.Descriptor instead.
func (*UploadVideoChunk) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{17}
}

func (x *UploadVideoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadVideoChunk) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_famfun_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{18}
}

func (x *UploadVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadVideoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadVideoResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeServerId  string                 `protobuf:"bytes,1,opt,name=home_server_id,json=homeServerId,proto3" json:"home_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_famfun_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{19}
}

func (x *ScanRequest) GetHomeServerId() string {
	if x != nil {
		return x.HomeServerId
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_famfun_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{20}
}

func (x *ScanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScanResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_RegisterRequest
	//	*Envelope_RegisterResponse
	//	*Envelope_HeartbeatRequest
	//	*Envelope_HeartbeatResponse
	//	*Envelope_VideoListUpdate
	//	*Envelope_GetPlaylistRequest
	//	*Envelope_GetPlaylistResponse
	//	*Envelope_GetSegmentRequest
	//	*Envelope_GetSegmentResponse
	//	*Envelope_GetVideoInfoRequest
	//	*Envelope_GetVideoInfoResponse
	//	*Envelope_GetThumbnailRequest
	//	*Envelope_GetThumbnailResponse
	//	*Envelope_UpdateVideoInfoRequest
	//	*Envelope_UpdateVideoInfoResponse
	//	*Envelope_UploadVideoRequest
	//	*Envelope_UploadVideoChunk
	//	*Envelope_UploadVideoResponse
	//	*Envelope_ScanRequest
	//	*Envelope_ScanResponse
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_famfun_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_famfun_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_famfun_proto_rawDescGZIP(), []int{21}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Envelope) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeatRequest() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HeartbeatRequest); ok {
			return x.HeartbeatRequest
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeatResponse() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HeartbeatResponse); ok {
			return x.HeartbeatResponse
		}
	}
	return nil
}

func (x *Envelope) GetVideoListUpdate() *VideoListUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_VideoListUpdate); ok {
			return x.VideoListUpdate
		}
	}
	return nil
}

func (x *Envelope) GetGetPlaylistRequest() *GetPlaylistRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetPlaylistRequest); ok {
			return x.GetPlaylistRequest
		}
	}
	return nil
}

func (x *Envelope) GetGetPlaylistResponse() *GetPlaylistResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetPlaylistResponse); ok {
			return x.GetPlaylistResponse
		}
	}
	return nil
}

func (x *Envelope) GetGetSegmentRequest() *GetSegmentRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetSegmentRequest); ok {
			return x.GetSegmentRequest
		}
	}
	return nil
}

func (x *Envelope) GetGetSegmentResponse() *GetSegmentResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetSegmentResponse); ok {
			return x.GetSegmentResponse
		}
	}
	return nil
}

func (x *Envelope) GetGetVideoInfoRequest() *GetVideoInfoRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetVideoInfoRequest); ok {
			return x.GetVideoInfoRequest
		}
	}
	return nil
}

func (x *Envelope) GetGetVideoInfoResponse() *GetVideoInfoResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetVideoInfoResponse); ok {
			return x.GetVideoInfoResponse
		}
	}
	return nil
}

func (x *Envelope) GetGetThumbnailRequest() *GetThumbnailRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetThumbnailRequest); ok {
			return x.GetThumbnailRequest
		}
	}
	return nil
}

func (x *Envelope) GetGetThumbnailResponse() *GetThumbnailResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetThumbnailResponse); ok {
			return x.GetThumbnailResponse
		}
	}
	return nil
}

func (x *Envelope) GetUpdateVideoInfoRequest() *UpdateVideoInfoRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UpdateVideoInfoRequest); ok {
			return x.UpdateVideoInfoRequest
		}
	}
	return nil
}

func (x *Envelope) GetUpdateVideoInfoResponse() *UpdateVideoInfoResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UpdateVideoInfoResponse); ok {
			return x.UpdateVideoInfoResponse
		}
	}
	return nil
}

func (x *Envelope) GetUploadVideoRequest() *UploadVideoRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UploadVideoRequest); ok {
			return x.UploadVideoRequest
		}
	}
	return nil
}

func (x *Envelope) GetUploadVideoChunk() *UploadVideoChunk {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UploadVideoChunk); ok {
			return x.UploadVideoChunk
		}
	}
	return nil
}

func (x *Envelope) GetUploadVideoResponse() *UploadVideoResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UploadVideoResponse); ok {
			return x.UploadVideoResponse
		}
	}
	return nil
}

func (x *Envelope) GetScanRequest() *ScanRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ScanRequest); ok {
			return x.ScanRequest
		}
	}
	return nil
}

func (x *Envelope) GetScanResponse() *ScanResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ScanResponse); ok {
			return x.ScanResponse
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_RegisterRequest struct {
	RegisterRequest *RegisterRequest `protobuf:"bytes,1,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Envelope_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,2,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type Envelope_HeartbeatRequest struct {
	HeartbeatRequest *HeartbeatRequest `protobuf:"bytes,3,opt,name=heartbeat_request,json=heartbeatRequest,proto3,oneof"`
}

type Envelope_HeartbeatResponse struct {
	HeartbeatResponse *HeartbeatResponse `protobuf:"bytes,4,opt,name=heartbeat_response,json=heartbeatResponse,proto3,oneof"`
}

type Envelope_VideoListUpdate struct {
	VideoListUpdate *VideoListUpdate `protobuf:"bytes,5,opt,name=video_list_update,json=videoListUpdate,proto3,oneof"`
}

type Envelope_GetPlaylistRequest struct {
	GetPlaylistRequest *GetPlaylistRequest `protobuf:"bytes,6,opt,name=get_playlist_request,json=getPlaylistRequest,proto3,oneof"`
}

type Envelope_GetPlaylistResponse struct {
	GetPlaylistResponse *GetPlaylistResponse `protobuf:"bytes,7,opt,name=get_playlist_response,json=getPlaylistResponse,proto3,oneof"`
}

type Envelope_GetSegmentRequest struct {
	GetSegmentRequest *GetSegmentRequest `protobuf:"bytes,8,opt,name=get_segment_request,json=getSegmentRequest,proto3,oneof"`
}

type Envelope_GetSegmentResponse struct {
	GetSegmentResponse *GetSegmentResponse `protobuf:"bytes,9,opt,name=get_segment_response,json=getSegmentResponse,proto3,oneof"`
}

type Envelope_GetVideoInfoRequest struct {
	GetVideoInfoRequest *GetVideoInfoRequest `protobuf:"bytes,10,opt,name=get_video_info_request,json=getVideoInfoRequest,proto3,oneof"`
}

type Envelope_GetVideoInfoResponse struct {
	GetVideoInfoResponse *GetVideoInfoResponse `protobuf:"bytes,11,opt,name=get_video_info_response,json=getVideoInfoResponse,proto3,oneof"`
}

type Envelope_GetThumbnailRequest struct {
	GetThumbnailRequest *GetThumbnailRequest `protobuf:"bytes,12,opt,name=get_thumbnail_request,json=getThumbnailRequest,proto3,oneof"`
}

type Envelope_GetThumbnailResponse struct {
	GetThumbnailResponse *GetThumbnailResponse `protobuf:"bytes,13,opt,name=get_thumbnail_response,json=getThumbnailResponse,proto3,oneof"`
}

type Envelope_UpdateVideoInfoRequest struct {
	UpdateVideoInfoRequest *UpdateVideoInfoRequest `protobuf:"bytes,14,opt,name=update_video_info_request,json=updateVideoInfoRequest,proto3,oneof"`
}

type Envelope_UpdateVideoInfoResponse struct {
	UpdateVideoInfoResponse *UpdateVideoInfoResponse `protobuf:"bytes,15,opt,name=update_video_info_response,json=updateVideoInfoResponse,proto3,oneof"`
}

type Envelope_UploadVideoRequest struct {
	UploadVideoRequest *UploadVideoRequest `protobuf:"bytes,16,opt,name=upload_video_request,json=uploadVideoRequest,proto3,oneof"`
}

type Envelope_UploadVideoChunk struct {
	UploadVideoChunk *UploadVideoChunk `protobuf:"bytes,17,opt,name=upload_video_chunk,json=uploadVideoChunk,proto3,oneof"`
}

type Envelope_UploadVideoResponse struct {
	UploadVideoResponse *UploadVideoResponse `protobuf:"bytes,18,opt,name=upload_video_response,json=uploadVideoResponse,proto3,oneof"`
}

type Envelope_ScanRequest struct {
	ScanRequest *ScanRequest `protobuf:"bytes,19,opt,name=scan_request,json=scanRequest,proto3,oneof"`
}

type Envelope_ScanResponse struct {
	ScanResponse *ScanResponse `protobuf:"bytes,20,opt,name=scan_response,json=scanResponse,proto3,oneof"`
}

func (*Envelope_RegisterRequest) isEnvelope_Payload() {}

func (*Envelope_RegisterResponse) isEnvelope_Payload() {}

func (*Envelope_HeartbeatRequest) isEnvelope_Payload() {}

func (*Envelope_HeartbeatResponse) isEnvelope_Payload() {}

func (*Envelope_VideoListUpdate) isEnvelope_Payload() {}

func (*Envelope_GetPlaylistRequest) isEnvelope_Payload() {}

func (*Envelope_GetPlaylistResponse) isEnvelope_Payload() {}

func (*Envelope_GetSegmentRequest) isEnvelope_Payload() {}

func (*Envelope_GetSegmentResponse) isEnvelope_Payload() {}

func (*Envelope_GetVideoInfoRequest) isEnvelope_Payload() {}

func (*Envelope_GetVideoInfoResponse) isEnvelope_Payload() {}

func (*Envelope_GetThumbnailRequest) isEnvelope_Payload() {}

func (*Envelope_GetThumbnailResponse) isEnvelope_Payload() {}

func (*Envelope_UpdateVideoInfoRequest) isEnvelope_Payload() {}

func (*Envelope_UpdateVideoInfoResponse) isEnvelope_Payload() {}

func (*Envelope_UploadVideoRequest) isEnvelope_Payload() {}

func (*Envelope_UploadVideoChunk) isEnvelope_Payload() {}

func (*Envelope_UploadVideoResponse) isEnvelope_Payload() {}

func (*Envelope_ScanRequest) isEnvelope_Payload() {}

func (*Envelope_ScanResponse) isEnvelope_Payload() {}

var File_famfun_proto protoreflect.FileDescriptor

const file_famfun_proto_rawDesc = "" +
	"\n" +
	"\ffamfun.proto\x12\x06famfun\"\xac\x02\n" +
	"\tVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\x12\x1a\n" +
	"\bfilesize\x18\x05 \x01(\x03R\bfilesize\x12\x1e\n" +
	"\n" +
	"resolution\x18\x06 \x01(\tR\n" +
	"resolution\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12$\n" +
	"\x0ehome_server_id\x18\b \x01(\tR\fhomeServerId\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"visibility\x18\n" +
	" \x01(\tR\n" +
	"visibility\"K\n" +
	"\x0fRegisterRequest\x12$\n" +
	"\x0ehome_server_id\x18\x01 \x01(\tR\fhomeServerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x10HeartbeatRequest\x12$\n" +
	"\x0ehome_server_id\x18\x01 \x01(\tR\fhomeServerId\x12\x1b\n" +
	"\tvideo_ids\x18\x02 \x03(\tR\bvideoIds\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"T\n" +
	"\x0fVideoListUpdate\x12$\n" +
	"\x0ehome_server_id\x18\x01 \x01(\tR\fhomeServerId\x12\x1b\n" +
	"\tvideo_ids\x18\x02 \x03(\tR\bvideoIds\"0\n" +
	"\x13GetVideoInfoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"o\n" +
	"\x14GetVideoInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12'\n" +
	"\x05video\x18\x03 \x01(\v2\x11.famfun.VideoInfoR\x05video\"0\n" +
	"\x13GetThumbnailRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"`\n" +
	"\x14GetThumbnailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"N\n" +
	"\x12GetPlaylistRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"~\n" +
	"\x13GetPlaylistResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"p\n" +
	"\x11GetSegmentRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12!\n" +
	"\fsegment_name\x18\x02 \x01(\tR\vsegmentName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"}\n" +
	"\x12GetSegmentResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"\x8b\x01\n" +
	"\x16UpdateVideoInfoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\"r\n" +
	"\x17UpdateVideoInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12'\n" +
	"\x05video\x18\x03 \x01(\v2\x11.famfun.VideoInfoR\x05video\"\xe5\x01\n" +
	"\x12UploadVideoRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfilesize\x18\x02 \x01(\x03R\bfilesize\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12$\n" +
	"\x0ehome_server_id\x18\x04 \x01(\tR\fhomeServerId\x12!\n" +
	"\ftotal_chunks\x18\x05 \x01(\rR\vtotalChunks\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"G\n" +
	"\x10UploadVideoChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\rR\n" +
	"chunkIndex\"`\n" +
	"\x13UploadVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\"3\n" +
	"\vScanRequest\x12$\n" +
	"\x0ehome_server_id\x18\x01 \x01(\tR\fhomeServerId\">\n" +
	"\fScanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb5\f\n" +
	"\bEnvelope\x12D\n" +
	"\x10register_request\x18\x01 \x01(\v2\x17.famfun.RegisterRequestH\x00R\x0fregisterRequest\x12G\n" +
	"\x11register_response\x18\x02 \x01(\v2\x18.famfun.RegisterResponseH\x00R\x10registerResponse\x12G\n" +
	"\x11heartbeat_request\x18\x03 \x01(\v2\x18.famfun.HeartbeatRequestH\x00R\x10heartbeatRequest\x12J\n" +
	"\x12heartbeat_response\x18\x04 \x01(\v2\x19.famfun.HeartbeatResponseH\x00R\x11heartbeatResponse\x12E\n" +
	"\x11video_list_update\x18\x05 \x01(\v2\x17.famfun.VideoListUpdateH\x00R\x0fvideoListUpdate\x12N\n" +
	"\x14get_playlist_request\x18\x06 \x01(\v2\x1a.famfun.GetPlaylistRequestH\x00R\x12getPlaylistRequest\x12Q\n" +
	"\x15get_playlist_response\x18\a \x01(\v2\x1b.famfun.GetPlaylistResponseH\x00R\x13getPlaylistResponse\x12K\n" +
	"\x13get_segment_request\x18\b \x01(\v2\x19.famfun.GetSegmentRequestH\x00R\x11getSegmentRequest\x12N\n" +
	"\x14get_segment_response\x18\t \x01(\v2\x1a.famfun.GetSegmentResponseH\x00R\x12getSegmentResponse\x12R\n" +
	"\x16get_video_info_request\x18\n" +
	" \x01(\v2\x1b.famfun.GetVideoInfoRequestH\x00R\x13getVideoInfoRequest\x12U\n" +
	"\x17get_video_info_response\x18\v \x01(\v2\x1c.famfun.GetVideoInfoResponseH\x00R\x14getVideoInfoResponse\x12Q\n" +
	"\x15get_thumbnail_request\x18\f \x01(\v2\x1b.famfun.GetThumbnailRequestH\x00R\x13getThumbnailRequest\x12T\n" +
	"\x16get_thumbnail_response\x18\r \x01(\v2\x1c.famfun.GetThumbnailResponseH\x00R\x14getThumbnailResponse\x12[\n" +
	"\x19update_video_info_request\x18\x0e \x01(\v2\x1e.famfun.UpdateVideoInfoRequestH\x00R\x16updateVideoInfoRequest\x12^\n" +
	"\x1aupdate_video_info_response\x18\x0f \x01(\v2\x1f.famfun.UpdateVideoInfoResponseH\x00R\x17updateVideoInfoResponse\x12N\n" +
	"\x14upload_video_request\x18\x10 \x01(\v2\x1a.famfun.UploadVideoRequestH\x00R\x12uploadVideoRequest\x12H\n" +
	"\x12upload_video_chunk\x18\x11 \x01(\v2\x18.famfun.UploadVideoChunkH\x00R\x10uploadVideoChunk\x12Q\n" +
	"\x15upload_video_response\x18\x12 \x01(\v2\x1b.famfun.UploadVideoResponseH\x00R\x13uploadVideoResponse\x128\n" +
	"\fscan_request\x18\x13 \x01(\v2\x13.famfun.ScanRequestH\x00R\vscanRequest\x12;\n" +
	"\rscan_response\x18\x14 \x01(\v2\x14.famfun.ScanResponseH\x00R\fscanResponseB\t\n" +
	"\apayloadB'Z%github.com/yingshulu/famfun/pkg/protob\x06proto3"

var (
	file_famfun_proto_rawDescOnce sync.Once
	file_famfun_proto_rawDescData []byte
)

func file_famfun_proto_rawDescGZIP() []byte {
	file_famfun_proto_rawDescOnce.Do(func() {
		file_famfun_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_famfun_proto_rawDesc), len(file_famfun_proto_rawDesc)))
	})
	return file_famfun_proto_rawDescData
}

var file_famfun_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_famfun_proto_goTypes = []any{
	(*VideoInfo)(nil),               // 0: famfun.VideoInfo
	(*RegisterRequest)(nil),         // 1: famfun.RegisterRequest
	(*RegisterResponse)(nil),        // 2: famfun.RegisterResponse
	(*HeartbeatRequest)(nil),        // 3: famfun.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 4: famfun.HeartbeatResponse
	(*VideoListUpdate)(nil),         // 5: famfun.VideoListUpdate
	(*GetVideoInfoRequest)(nil),     // 6: famfun.GetVideoInfoRequest
	(*GetVideoInfoResponse)(nil),    // 7: famfun.GetVideoInfoResponse
	(*GetThumbnailRequest)(nil),     // 8: famfun.GetThumbnailRequest
	(*GetThumbnailResponse)(nil),    // 9: famfun.GetThumbnailResponse
	(*GetPlaylistRequest)(nil),      // 10: famfun.GetPlaylistRequest
	(*GetPlaylistResponse)(nil),     // 11: famfun.GetPlaylistResponse
	(*GetSegmentRequest)(nil),       // 12: famfun.GetSegmentRequest
	(*GetSegmentResponse)(nil),      // 13: famfun.GetSegmentResponse
	(*UpdateVideoInfoRequest)(nil),  // 14: famfun.UpdateVideoInfoRequest
	(*UpdateVideoInfoResponse)(nil), // 15: famfun.UpdateVideoInfoResponse
	(*UploadVideoRequest)(nil),      // 16: famfun.UploadVideoRequest
	(*UploadVideoChunk)(nil),        // 17: famfun.UploadVideoChunk
	(*UploadVideoResponse)(nil),     // 18: famfun.UploadVideoResponse
	(*ScanRequest)(nil),             // 19: famfun.ScanRequest
	(*ScanResponse)(nil),            // 20: famfun.ScanResponse
	(*Envelope)(nil),                // 21: famfun.Envelope
}
var file_famfun_proto_depIdxs = []int32{
	0,  // 0: famfun.GetVideoInfoResponse.video:type_name -> famfun.VideoInfo
	0,  // 1: famfun.UpdateVideoInfoResponse.video:type_name -> famfun.VideoInfo
	1,  // 2: famfun.Envelope.register_request:type_name -> famfun.RegisterRequest
	2,  // 3: famfun.Envelope.register_response:type_name -> famfun.RegisterResponse
	3,  // 4: famfun.Envelope.heartbeat_request:type_name -> famfun.HeartbeatRequest
	4,  // 5: famfun.Envelope.heartbeat_response:type_name -> famfun.HeartbeatResponse
	5,  // 6: famfun.Envelope.video_list_update:type_name -> famfun.VideoListUpdate
	10, // 7: famfun.Envelope.get_playlist_request:type_name -> famfun.GetPlaylistRequest
	11, // 8: famfun.Envelope.get_playlist_response:type_name -> famfun.GetPlaylistResponse
	12, // 9: famfun.Envelope.get_segment_request:type_name -> famfun.GetSegmentRequest
	13, // 10: famfun.Envelope.get_segment_response:type_name -> famfun.GetSegmentResponse
	6,  // 11: famfun.Envelope.get_video_info_request:type_name -> famfun.GetVideoInfoRequest
	7,  // 12: famfun.Envelope.get_video_info_response:type_name -> famfun.GetVideoInfoResponse
	8,  // 13: famfun.Envelope.get_thumbnail_request:type_name -> famfun.GetThumbnailRequest
	9,  // 14: famfun.Envelope.get_thumbnail_response:type_name -> famfun.GetThumbnailResponse
	14, // 15: famfun.Envelope.update_video_info_request:type_name -> famfun.UpdateVideoInfoRequest
	15, // 16: famfun.Envelope.update_video_info_response:type_name -> famfun.UpdateVideoInfoResponse
	16, // 17: famfun.Envelope.upload_video_request:type_name -> famfun.UploadVideoRequest
	17, // 18: famfun.Envelope.upload_video_chunk:type_name -> famfun.UploadVideoChunk
	18, // 19: famfun.Envelope.upload_video_response:type_name -> famfun.UploadVideoResponse
	19, // 20: famfun.Envelope.scan_request:type_name -> famfun.ScanRequest
	20, // 21: famfun.Envelope.scan_response:type_name -> famfun.ScanResponse
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_famfun_proto_init() }
func file_famfun_proto_init() {
	if File_famfun_proto != nil {
		return
	}
	file_famfun_proto_msgTypes[21].OneofWrappers = []any{
		(*Envelope_RegisterRequest)(nil),
		(*Envelope_RegisterResponse)(nil),
		(*Envelope_HeartbeatRequest)(nil),
		(*Envelope_HeartbeatResponse)(nil),
		(*Envelope_VideoListUpdate)(nil),
		(*Envelope_GetPlaylistRequest)(nil),
		(*Envelope_GetPlaylistResponse)(nil),
		(*Envelope_GetSegmentRequest)(nil),
		(*Envelope_GetSegmentResponse)(nil),
		(*Envelope_GetVideoInfoRequest)(nil),
		(*Envelope_GetVideoInfoResponse)(nil),
		(*Envelope_GetThumbnailRequest)(nil),
		(*Envelope_GetThumbnailResponse)(nil),
		(*Envelope_UpdateVideoInfoRequest)(nil),
		(*Envelope_UpdateVideoInfoResponse)(nil),
		(*Envelope_UploadVideoRequest)(nil),
		(*Envelope_UploadVideoChunk)(nil),
		(*Envelope_UploadVideoResponse)(nil),
		(*Envelope_ScanRequest)(nil),
		(*Envelope_ScanResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_famfun_proto_rawDesc), len(file_famfun_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_famfun_proto_goTypes,
		DependencyIndexes: file_famfun_proto_depIdxs,
		MessageInfos:      file_famfun_proto_msgTypes,
	}.Build()
	File_famfun_proto = out.File
	file_famfun_proto_goTypes = nil
	file_famfun_proto_depIdxs = nil
}
